config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "admin" => "admin/static_pages#home"

  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup"  => "users#new"

  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"

  get "following/index"
  get "followers/index"

  resources :users do
    resources :followers, only: [:index]
    resources :followings, only: [:index]
  end

  resources :relationships, only: [:create, :destroy, :show]

  resources :categories do
    resources :lessons
  end
  resources :words
  resources :results
  resources :activities

  namespace :admin do
    resources :users do
      resources :activities
    end
    resources :categories do
      resources :words
    end
    resources :words
  end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < ApplicationController
  def home; end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @activities = current_user.feed.paginate page: params[:page] if logged_in?
  end

  def help; end

  def about; end

  def contact; end
end

app/helpers/admin/static_pages_helper.rb
module Admin::StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>

app/views/static_pages/home.html.erb
 <% provide(:title, "Home") %>
 <% if logged_in? %>
  <% @user ||= current_user %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
    </aside>
    <div class="col-md-8">
      <div>
        <div class="col-md-6">
          <%= button_to "Words", words_path, method: "get", class: "btn btn-primary" %>
        </div>
        <div class="col-md-6">
          <%= button_to "Lesson", categories_path, method: "get", class: "btn btn-primary" %>
        </div>
      </div>
      <% if @activities.any? %>
        <hr><h3>Feeds</h3>
        <ol class="entries">
          <%= render @activities %>
        </ol>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the E-learning</h1>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>