config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "admin" => "admin/static_pages#home"

  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup"  => "users#new"

  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"

  get "following/index"
  get "followers/index"

  resources :users do
    resources :followers, only: [:index]
    resources :followings, only: [:index]
  end

  resources :relationships, only: [:create, :destroy, :show]

  resources :categories do
    resources :lessons
  end
  resources :words
  resources :results
  resources :activities

  namespace :admin do
    resources :users do
      resources :activities
    end
    resources :categories do
      resources :words
    end
    resources :words
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :answers, dependent: :destroy

  validates :category_id, presence: true
  validates :japanese, presence: true
  validates :japanese, uniqueness: { scope: :category_id, case_sensitive: false }

  accepts_nested_attributes_for :answers, reject_if: ->(a) { a[:content].blank? }, allow_destroy: true

  def correct_answer
    answers.find_by correct: true
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  def index
    if params[:category_id].blank?
      @words = Word.paginate page: params[:page], per_page: 100
    else
      category = Category.find params[:category_id]
      @words = category.words.paginate page: params[:page], per_page: 100
    end
  end

  def new
    if params[:category_id].blank?
      @word = Word.new
    else
      @category = Category.find params[:category_id]
      @word = @category.words.new
    end
    4.times { @word.answers.build }
  end

  def edit
    if params[:category_id].blank?
      @word = Word.find params[:id]
    else
      @category = Category.find params[:category_id]
      @word = @category.words.find params[:id]
    end
  end

  def create
    @word = if category
              @category.words.new word_params
            else
              Word.new word_params
            end

    if @word.save
      redirect_to admin_categories_path, success: "New word created!"
    else
      render :new
    end
  end

  def update
    @word = Word.find params[:id]
    if @word.update word_params
      flash[:success] = "Word updated"
      redirect_to admin_words_url
    else
      render :edit
    end
  end

  def destroy
    Word.find(params[:id]).destroy
    flash[:success] = "Word deleted"
    redirect_to admin_words_url
  end

  private

  def word_params
    params.require(:word).permit :japanese, :category_id, answers_attributes: [:id, :content, :correct, :_destroy]
  end

  def category
    @category ||= Category.find params[:category_id] if params[:category_id].present?
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user

  def index
    if params[:category_id].blank?
      @words = Word.paginate page: params[:page], per_page: 100
    else
      category = Category.find params[:category_id]
      @words = category.words.paginate page: params[:page], per_page: 100
    end
  end
end

app/helpers/admin/words_helper.rb
module Admin::WordsHelper
end

app/views/admin/words/_answer_fields.html.erb
<div class="fields">
  <p class="col-md-6">
    Content <%= f.text_field :content, class: "form-control" %>
    Correct? <%= f.check_box :correct %>
    <%= link_to_remove_fields "Remove", f %>
  </p>
</div>

app/views/admin/words/_word.html.erb
<li id="word-<%= word.id %>">
  <span class="col-md-3">
    <%= word.japanese %>
    <%= link_to " ||edit", edit_admin_word_path(word) %>
    <%= link_to " ||delete", admin_word_path(word),
                    method: :delete, data: {confirm: "You sure?"} %>
  </span>
  <span class="col-md-3"><%= word.correct_answer.content %></span>
</li>

app/views/admin/words/edit.html.erb
<% provide(:title, 'Edit word') %>
<h1>Add new word</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @word] do |f| %>
      <%= render 'shared/word_error_messages' %>
      <% if params[:category_id].blank? %>
        <%= f.select :category_id, Category.all.collect{|p| [p.title, p.id]}, include_blank: true %>
      <% end %>  
      <%= f.label :Word %>
      <%= f.text_field :japanese, class: 'form-control'%>
      <%= f.label :Answers %>
        <%= f.fields_for :answers do |builder| %>
          <%= render 'answer_fields', f: builder %>
        <% end %>
        <p>
          <%= link_to_add_fields "Add Answer", f, :answers %>
        </p>
      <%= f.submit "Edit word", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/words/index.html.erb
<% provide(:title, "Words") %>
<div>
  <%= form_tag nil, method: 'get', class: 'tag_form' do %>
    <%= select_tag "category_id", options_from_collection_for_select(Category.all, :id, :title), prompt: "Select category" %>
    <%= submit_tag "Filter category" %>
  <% end %>
</div>
<div>
  <ul class="word" style="list-style-type:none" >
    <li>
      <b>
        <span class="col-md-3">Word</span>
        <span class="col-md-3">Answer</span>
        <span class="col-md-3">Word</span>
        <span class="col-md-3">Answer</span>
      </b>
    </li>
    <%= render @words %>
  </ul>
  <%= will_paginate @words %>
</div>

app/views/admin/words/new.html.erb
<% provide(:title, 'Add new word') %>
<h1>Add new word</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if params[:category_id].blank? %>
      <%= form_for [:admin, @word] do |f| %>
        <%= render 'shared/word_error_messages' %>
        <% if params[:category_id].blank? %>
          <%= f.select :category_id, Category.all.collect{|p| [p.title, p.id]}, include_blank: true %>
        <% end %>  
        <%= f.label :Word %>
        <%= f.text_field :japanese, class: 'form-control'%>
        <%= f.label :Answers %>
        <%= f.fields_for :answers do |builder| %>
          <%= render 'answer_fields', f: builder %>
        <% end %>
        <p>
          <%= link_to_add_fields "Add Answer", f, :answers %>
        </p>
        <%= f.submit "Create new word", class: "btn btn-primary" %>
      <% end %>
    <% else %>
      <%= form_for [:admin, @category, @word] do |f| %>
        <%= render 'shared/word_error_messages' %>
        <%= f.label :Word %>
        <%= f.text_field :japanese, class: 'form-control'%>
        <%= f.label :Answers %>
        <%= f.fields_for :answers do |builder| %>
          <%= render 'answer_fields', f: builder %>
        <% end %>
        <p>
          <%= link_to_add_fields "Add Answer", f, :answers %>
        </p>
        <%= f.submit "Create new word", class: "btn btn-primary" %>
      <% end %>
    <% end %>  
  </div>
</div>