config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "admin" => "admin/static_pages#home"

  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup"  => "users#new"

  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"

  get "following/index"
  get "followers/index"

  resources :users do
    resources :followers, only: [:index]
    resources :followings, only: [:index]
  end

  resources :relationships, only: [:create, :destroy, :show]

  resources :categories do
    resources :lessons
  end
  resources :words
  resources :results
  resources :activities

  namespace :admin do
    resources :users do
      resources :activities
    end
    resources :categories do
      resources :words
    end
    resources :words
  end
end

app/views/shared/_category_error_messages.html.erb
<% if @category.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@category.errors.count, "error") %>.
    </div>
    <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_follow_user.html.erb
<h3><%= @title %></h3>
<% if @users.any? %>
  <%= will_paginate @users %>
  <ul class="users follow">
    <%= render @users %>
  </ul>
  <%= will_paginate @users %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= user_followings_path(@user) %>" >
    <%= hidden_field_tag ':follower_id', @user.id %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= user_followers_path(@user) %>" >
    <%= hidden_field_tag ':followed_id', @user.id %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<h1>
  <%= link_to gravatar_for(@user, size: 50), @user %>
  <%= @user.name %>
</h1>
<%= link_to_if(logged_in? && current_user?(@user), "edit", edit_user_path(@user)){} %>
<%= link_to_if(logged_in? && current_user?(@user), "|| profile", @user){} %>
<%= link_to_if(logged_in_admin? && !current_user?(@user), "|| delete", admin_user_path(@user),
                            method: :delete, data: {confirm: "you sure?"}){} %>

app/views/shared/_word_error_messages.html.erb
<% if @word.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@word.errors.count, "error") %>.
    </div>
    <ul>
    <% @word.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>