config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "admin" => "admin/static_pages#home"

  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup"  => "users#new"

  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"

  get "following/index"
  get "followers/index"

  resources :users do
    resources :followers, only: [:index]
    resources :followings, only: [:index]
  end

  resources :relationships, only: [:create, :destroy, :show]

  resources :categories do
    resources :lessons
  end
  resources :words
  resources :results
  resources :activities

  namespace :admin do
    resources :users do
      resources :activities
    end
    resources :categories do
      resources :words
    end
    resources :words
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy, inverse_of: false
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy, inverse_of: false
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  has_many :lessons, dependent: :destroy
  has_many :activities, dependent: :destroy

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create string, cost: cost
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update remember_digest: User.digest(remember_token)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password? remember_token
  end

  def forget
    update remember_digest: nil
  end

  def follow(other_user)
    active_relationships.create followed: other_user
    activities.create target_id: other_user.id, action_type: "follow"
  end

  def unfollow(other_user)
    active_relationships.find_by(followed: other_user).destroy
    activities.create target_id: other_user.id, action_type: "unfollow"
  end

  def following?(other_user)
    following.include? other_user
  end

  def feed
    following_ids = following.pluck :id
    Activity.where user_id: following_ids + [id]
  end

  def user_activity
    Activity.where user: self
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :logged_in_user

  def new
    @user = User.new
  end

  def index
    @users = User.paginate page: params[:page], per_page: 10
    @total = User.all.count
  end

  def show
    @user = User.find params[:id]
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "New user created!"
      redirect_to admin_users_path
    else
      render "new"
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update user_params
      flash[:success] = "Profile updated!"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    flash[:success] = "User deleted!"
    redirect_to admin_users_url
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]
  before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def index
    @users = User.paginate page: params[:page]
  end

  def show
    @user = User.find params[:id]
    @unfollow = current_user.active_relationships.find_by followed: @user
    @follow = current_user.active_relationships.build
    @activities = @user.feed.paginate page: params[:page]
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      remember @user
      flash[:success] = "Welcome to the E-Learning"
      redirect_to user_url(@user)
    else
      render "new"
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update user_params
      flash[:success] = "Profile updated!"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    flash[:success] = "User deleted!"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end

  def correct_user
    @user = User.find params[:id]
    redirect_to root_url unless current_user? @user
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/admin/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <%= link_to " || activities", admin_user_activities_path(user) %>
  <% if !current_user?(user)%>
    <%= link_to " || delete", admin_user_path(user), method: :delete, data: {confirm: "you sure?"} %>
  <% end %>
</li>

app/views/admin/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([:admin, @user]) do |f| %>
      <%= render 'shared/user_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user, size: 50 %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All <%= @total %> users</h1>
<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <%= render user  if current_user != user %>
  <% end %>
</ul>

<%= will_paginate %>
<%= link_to "Create new user", new_admin_user_path %>

app/views/admin/users/new.html.erb
<% provide(:title, 'Add new user') %>
<h1>Add new user</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([:admin, @user]) do |f| %>
      <%= render 'shared/user_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'%>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>  
    </section>
  </aside>
  <div class="col-md-8">
    
  </div>
</div>